In [53]:
import os
import numpy as np

import keras
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten, Conv2D, MaxPooling2D
from sklearn.metrics import accuracy_score

## Download dataset 
https://drive.google.com/drive/u/3/folders/1sHh6NvuKX6RB5OytLwf4kaqfQ9svJNDQ

## Load data

In [54]:
x_train = np.load("x_train.npy")
y_train = np.load("y_train.npy")

x_test = np.load("x_test.npy")
y_test = np.load("y_test.npy")

print(x_train.shape, 'train samples')
print(x_test.shape[0], 'test samples')

(50000, 32, 32, 3) train samples
10000 test samples


In [55]:
# It's a multi-class classification problem 
class_index = {'airplane': 0, 'automobile': 1, 'bird': 2, 'cat': 3, 'deer': 4,
               'dog': 5, 'frog': 6,'horse': 7,'ship': 8, 'truck': 9}
print(np.unique(y_train))

[0 1 2 3 4 5 6 7 8 9]


![image](https://img-blog.csdnimg.cn/20190623084800880.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3lqcDE5ODcxMDEz,size_16,color_FFFFFF,t_70)

## Data preprocess

In [56]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

# Convert class vectors to one-hot encoding (keras model requires one-hot label as inputs)
num_classes = 10
print(y_train[0])
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)
print(y_train[0])

[9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


## Build model & training (Keras)

In [57]:
# Builde model
model = Sequential() # Sequential groups a linear stack of layers 
model.add(Conv2D(filters=32, kernel_size=(3, 3), input_shape=x_train.shape[1:])) # Add Convolution layers
model.add(Activation('relu')) # Add Relu activation for non-linearity
model.add(Conv2D(filters=32, kernel_size=(3, 3))) # Add Convolution layers
model.add(Activation('relu')) # Add Relu activation for non-linearity
model.add(MaxPooling2D(pool_size=(4, 4))) # Add Max pooling to lower the sptail dimension

model.add(Flatten()) # Flatten the featuremaps
model.add(Dense(units=512)) # Add dense layer with 512 neurons
model.add(Activation('relu')) # Add Relu activation for non-linearity
model.add(Dense(units=num_classes)) # Add final output layer for 10 classes
model.add(Activation('softmax')) # Add softmax activation to transfer logits into probabilities

# initiate SGD optimizer
opt = keras.optimizers.SGD()

# Compile the model with loss function and optimizer, and evaluate with accuracy
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

# Setup some hyperparameters
batch_size = 32
epochs = 10

# Fit the data into model
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          validation_data=(x_test, y_test),
          shuffle=True)


Epoch 1/10
1563/1563 [==============================] - 36s 23ms/step - loss: 1.8568 - accuracy: 0.3341 - val_loss: 1.6674 - val_accuracy: 0.3909
Epoch 2/10
1563/1563 [==============================] - 34s 22ms/step - loss: 1.4402 - accuracy: 0.4909 - val_loss: 1.4348 - val_accuracy: 0.5019
Epoch 3/10
1563/1563 [==============================] - 37s 24ms/step - loss: 1.2805 - accuracy: 0.5490 - val_loss: 1.2788 - val_accuracy: 0.5602
Epoch 4/10
1563/1563 [==============================] - 40s 25ms/step - loss: 1.1737 - accuracy: 0.5872 - val_loss: 1.1629 - val_accuracy: 0.5982
Epoch 5/10
1563/1563 [==============================] - 42s 27ms/step - loss: 1.0884 - accuracy: 0.6211 - val_loss: 1.1319 - val_accuracy: 0.6059
Epoch 6/10
1563/1563 [==============================] - 44s 28ms/step - loss: 1.0117 - accuracy: 0.6486 - val_loss: 1.1308 - val_accuracy: 0.6066
Epoch 7/10
1563/1563 [==============================] - 42s 27ms/step - loss: 0.9390 - accuracy: 0.6750 - val_loss: 1.0030 -

In [58]:
y_pred = model.predict(x_test)
print(y_pred.shape) # 10000 samples, each sample with probaility of 10 classes

(10000, 10)


In [59]:
y_pred[0] 

array([5.8038253e-03, 1.8562093e-01, 1.1983217e-04, 4.6050823e-03,
       9.3595627e-05, 1.8896112e-04, 4.5562211e-07, 4.0878102e-04,
       2.2367632e-03, 8.0092180e-01], dtype=float32)

In [60]:
np.argmax(y_pred[0]) # argmax to find the predict class with highest probability. 9=truck

9

In [61]:
y_pred = np.argmax(y_pred, axis=1)

## DO NOT MODIFY CODE BELOW!
**Please screen shot your results and post it on your report**

In [62]:
y_pred = model.predict(x_test)
y_pred = np.argmax(y_pred, axis=1)

In [63]:
assert y_pred.shape == (10000, )

In [64]:
y_test = np.load("y_test.npy")
print("Accuracy of my model on test set: ", accuracy_score(y_test, y_pred))

Accuracy of my model on test set:  0.6603
